#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT/corporate/.env"
COMPOSE_FILE="$ROOT/corporate/docker-compose.yml"
HTTPS_COMPOSE_FILE="$ROOT/corporate/docker-compose.https.yml"
BACKUP_ROOT="$ROOT/corporate/backups"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE does not exist." >&2
  echo "Run ./install-linux.sh first." >&2
  exit 1
fi

DOCKER=(docker)
if ! docker info >/dev/null 2>&1; then
  if command -v sudo >/dev/null 2>&1 && sudo docker info >/dev/null 2>&1; then
    DOCKER=(sudo docker)
  else
    echo "ERROR: cannot connect to Docker." >&2
    exit 1
  fi
fi

# corporate/.env is generated by install-linux.sh and contains only shell-safe values.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

POSTGRES_USER="${POSTGRES_USER:-ctracking}"
POSTGRES_DB="${POSTGRES_DB:-ctracking}"
BIBO_PORT="${BIBO_PORT:-8081}"
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-http://localhost:$BIBO_PORT}"
DOMAIN="${DOMAIN:-}"

compose() {
  local args=(--env-file "$ENV_FILE" -f "$COMPOSE_FILE")
  if [[ -n "$DOMAIN" ]]; then
    args+=(-f "$HTTPS_COMPOSE_FILE")
  fi
  "${DOCKER[@]}" compose "${args[@]}" "$@"
}

health() {
  local url="http://127.0.0.1:$BIBO_PORT/healthz"
  if command -v curl >/dev/null 2>&1; then
    curl -fsS "$url"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$url"
  else
    "${DOCKER[@]}" inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' bibotracking
  fi
}

wait_healthy() {
  local ok=0
  for _ in $(seq 1 60); do
    if health >/dev/null 2>&1; then ok=1; break; fi
    sleep 2
  done
  if (( ! ok )); then
    echo "ERROR: BiBoTracking did not become healthy." >&2
    compose ps >&2 || true
    compose logs --tail=120 bibotracking >&2 || true
    return 1
  fi
}

cmd_status() {
  compose ps
  echo
  if health >/dev/null 2>&1; then
    echo "Health: OK"
    echo "Admin:  $PUBLIC_ORIGIN/admin/"
    if [[ -n "$DOMAIN" ]]; then
      echo "HTTPS:  Caddy enabled for $DOMAIN"
    fi
  else
    echo "Health: FAILED"
    return 1
  fi
}

cmd_update() {
  cd "$ROOT"
  if command -v git >/dev/null 2>&1 && [[ -d .git ]]; then
    echo "Updating repository..."
    git pull --ff-only
  fi

  echo "Updating Docker images..."
  compose pull db
  if [[ -n "$DOMAIN" ]]; then
    compose pull caddy
  fi
  if compose pull bibotracking; then
    compose up -d --no-build
  else
    echo "Prebuilt app image unavailable; building locally..."
    compose build --pull bibotracking
    compose up -d
  fi
  wait_healthy
  echo "Updated successfully: $PUBLIC_ORIGIN/admin/"
}

cmd_backup() {
  command -v gzip >/dev/null 2>&1 || { echo "ERROR: gzip is required." >&2; exit 1; }
  mkdir -p "$BACKUP_ROOT"
  chmod 700 "$BACKUP_ROOT" 2>/dev/null || true
  local stamp dir
  stamp="$(date +%Y%m%d-%H%M%S)"
  dir="$BACKUP_ROOT/$stamp"
  mkdir -p "$dir"
  chmod 700 "$dir" 2>/dev/null || true

  echo "Backing up PostgreSQL..."
  compose exec -T db pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB" | gzip -9 > "$dir/database.sql.gz"

  echo "Backing up screenshots, JWT config and logs..."
  "${DOCKER[@]}" run --rm \
    --volumes-from bibotracking \
    -v "$dir:/backup" \
    alpine:3.20 sh -c 'cd /app && tar -czf /backup/appdata.tar.gz storage config logs'

  cp "$ENV_FILE" "$dir/env.snapshot"
  chmod 600 "$dir/env.snapshot" 2>/dev/null || true

  cat > "$dir/README.txt" <<EOF
BiBoTracking Corporate backup
Created: $(date -Is 2>/dev/null || date)
Source: $PUBLIC_ORIGIN
Files:
- database.sql.gz   PostgreSQL dump
- appdata.tar.gz    screenshots/config/logs volumes
- env.snapshot      deployment configuration (contains secrets)
EOF

  echo "Backup created: $dir"
}

cmd_restore() {
  local dir="${1:-}"
  local confirm="${2:-}"
  if [[ -z "$dir" || ! -d "$dir" ]]; then
    echo "Usage: ./biboctl.sh restore <backup-directory> --yes" >&2
    exit 2
  fi
  if [[ "$confirm" != "--yes" ]]; then
    echo "Restore is destructive for the current database/app data." >&2
    echo "Re-run with --yes:" >&2
    echo "  ./biboctl.sh restore '$dir' --yes" >&2
    exit 2
  fi
  [[ -f "$dir/database.sql.gz" ]] || { echo "ERROR: database.sql.gz not found." >&2; exit 1; }
  [[ -f "$dir/appdata.tar.gz" ]] || { echo "ERROR: appdata.tar.gz not found." >&2; exit 1; }

  echo "Stopping application writes..."
  compose stop bibotracking || true
  compose up -d db

  echo "Restoring PostgreSQL..."
  compose exec -T db psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
    -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;'
  gzip -dc "$dir/database.sql.gz" | compose exec -T db psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1

  echo "Restoring screenshots/config/logs..."
  "${DOCKER[@]}" run --rm \
    --volumes-from bibotracking \
    -v "$dir:/backup:ro" \
    alpine:3.20 sh -c 'rm -rf /app/storage/* /app/config/* /app/logs/* && tar -xzf /backup/appdata.tar.gz -C /app'

  compose up -d
  wait_healthy
  echo "Restore completed: $PUBLIC_ORIGIN/admin/"
}

usage() {
  cat <<'EOF'
Usage: ./biboctl.sh COMMAND [args]

Commands:
  status                     Show containers, health and admin URL
  logs [service]             Follow logs (default: bibotracking; use caddy for TLS logs)
  start                      Start stack
  stop                       Stop stack without deleting it
  restart                    Restart stack and wait for health
  update                     git pull + pull/build images + restart
  backup                     Backup PostgreSQL + screenshots/config/logs
  restore DIR --yes          Restore a backup directory
  down                       Stop/remove containers (keeps volumes/data)
  config                     Render effective Docker Compose config
EOF
}

case "${1:-}" in
  status) cmd_status ;;
  logs) compose logs -f --tail=200 "${2:-bibotracking}" ;;
  start) compose up -d; wait_healthy; cmd_status ;;
  stop) compose stop ;;
  restart) compose restart; wait_healthy; cmd_status ;;
  update) cmd_update ;;
  backup) cmd_backup ;;
  restore) cmd_restore "${2:-}" "${3:-}" ;;
  down) compose down ;;
  config) compose config ;;
  -h|--help|help|"") usage ;;
  *) echo "Unknown command: $1" >&2; usage >&2; exit 2 ;;
esac
